//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWsREST {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleAppWsREST.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;operacao&quot;:&quot;antecipacao&quot;,
        ///	&quot;versao&quot;:&quot;1.0.0&quot;,
        ///	&quot;id_processo&quot;:&quot;|id|&quot;,
        ///	&quot;filial&quot;:&quot;|filial|&quot;, 
        ///	&quot;cnpj&quot;:&quot;|cnpj|&quot;,
        ///	&quot;prefixo&quot;:&quot;|prefixo|&quot;, 
        ///	&quot;numero&quot;:&quot;|numero|&quot; ,
        ///	&quot;parcela&quot;:&quot;|parcela|&quot;,
        ///	&quot;tipo&quot;:&quot;|tipo|&quot;, 
        ///	&quot;cliente&quot;:&quot;|cliente|&quot;,
        ///	&quot;loja_cli&quot;:&quot;|loja_cli|&quot;, 
        ///	&quot;banco&quot;:&quot;|banco|&quot;,  
        ///	&quot;agencia&quot;:&quot;|agencia|&quot;, 
        ///	&quot;conta&quot;:&quot;|conta|&quot;,
        ///	&quot;dt_pg_antecip&quot;:&quot;|dt_pg_antecip|&quot;, 
        ///	&quot;vlr_antecip&quot;:|vlr_antecip| 
        ///}.
        /// </summary>
        internal static string json_antecipacao {
            get {
                return ResourceManager.GetString("json_antecipacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;versao&quot;:&quot;1.0.0&quot;,
        ///	&quot;id_banco&quot;:&quot;|id|&quot;,
        ///	&quot;banco&quot;:&quot;|banco|&quot;, 
        ///	&quot;agencia&quot;:&quot;|agencia|&quot;,
        ///	&quot;dig_agencia&quot;:&quot;|dig_agencia|&quot;, 
        ///	&quot;contacorrente&quot;:&quot;|contacorrente|&quot; ,
        ///	&quot;dig_contacorrente&quot;:&quot;|dig_contacorrente|&quot; 
        ///}.
        /// </summary>
        internal static string json_banco {
            get {
                return ResourceManager.GetString("json_banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;operacao&quot;:&quot;bonificacao&quot;,
        ///	&quot;versao&quot;:&quot;1.0.0&quot;,
        ///	&quot;id_processo&quot;:&quot;|id|&quot;,
        ///	&quot;filial&quot;:&quot;|filial|&quot;, 
        ///	&quot;cnpj&quot;:&quot;|cnpj|&quot;,
        ///	&quot;prefixo&quot;:&quot;|prefixo|&quot;, 
        ///	&quot;numero&quot;:&quot;|numero|&quot; ,
        ///	&quot;parcela&quot;:&quot;|parcela|&quot;,
        ///	&quot;tipo&quot;:&quot;|tipo|&quot;, 
        ///	&quot;cliente&quot;:&quot;|cliente|&quot;,
        ///	&quot;loja_cli&quot;:&quot;|loja_cli|&quot;, 
        ///	&quot;dt_bonificacao&quot;:&quot;|dt_bonificacao|&quot;,
        ///	&quot;vlr_bonif&quot;:|vlr_bonif|
        ///}.
        /// </summary>
        internal static string json_bonificacao {
            get {
                return ResourceManager.GetString("json_bonificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;operacao&quot;:&quot;cancelamento&quot;,
        ///	&quot;versao&quot;:&quot;1.0.0&quot;,
        ///	&quot;id_processo&quot;:&quot;|id|&quot;,
        ///	&quot;filial&quot;:&quot;|filial|&quot;, 
        ///	&quot;cnpj&quot;:&quot;|cnpj|&quot;,
        ///	&quot;prefixo&quot;:&quot;|prefixo|&quot;, 
        ///	&quot;numero&quot;:&quot;|numero|&quot; ,
        ///	&quot;parcela&quot;:&quot;|parcela|&quot;,
        ///	&quot;tipo&quot;:&quot;|tipo|&quot;, 
        ///	&quot;cliente&quot;:&quot;|cliente|&quot;,
        ///	&quot;loja_cli&quot;:&quot;|loja_cli|&quot; 
        ///}.
        /// </summary>
        internal static string json_cancelamento {
            get {
                return ResourceManager.GetString("json_cancelamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;operacao&quot;:&quot;conciliacao&quot;,
        ///	&quot;versao&quot;:&quot;1.0.0&quot;,
        ///	&quot;id_processo&quot;:&quot;|id|&quot;,
        ///	&quot;filial&quot;:&quot;|filial|&quot;, 
        ///	&quot;cnpj&quot;:&quot;|cnpj|&quot;,
        ///	&quot;prefixo&quot;:&quot;|prefixo|&quot;, 
        ///	&quot;numero&quot;:&quot;|numero|&quot; ,
        ///	&quot;parcela&quot;:&quot;|parcela|&quot;,
        ///	&quot;tipo&quot;:&quot;|tipo|&quot;, 
        ///	&quot;cliente&quot;:&quot;|cliente|&quot;,
        ///	&quot;loja_cli&quot;:&quot;|loja_cli|&quot;, 
        ///	&quot;tipo_conciliacao&quot;:&quot;|tipo_conciliacao|&quot; 
        ///}.
        /// </summary>
        internal static string json_conciliacao {
            get {
                return ResourceManager.GetString("json_conciliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;operacao&quot;:&quot;coobrigacao&quot;,
        ///	&quot;versao&quot;:&quot;1.0.0&quot;,
        ///	&quot;id_processo&quot;:&quot;|id|&quot;,
        ///	&quot;filial&quot;:&quot;|filial|&quot;, 
        ///	&quot;cnpj&quot;:&quot;|cnpj|&quot;,
        ///	&quot;prefixo&quot;:&quot;|prefixo|&quot;, 
        ///	&quot;numero&quot;:&quot;|numero|&quot; ,
        ///	&quot;parcela&quot;:&quot;|parcela|&quot;,
        ///	&quot;tipo&quot;:&quot;|tipo|&quot;, 
        ///	&quot;cliente&quot;:&quot;|cliente|&quot;,
        ///	&quot;loja_cli&quot;:&quot;|loja_cli|&quot; 
        ///}.
        /// </summary>
        internal static string json_coobrigacao {
            get {
                return ResourceManager.GetString("json_coobrigacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;operacao&quot;:&quot;devolucao&quot;,
        ///	&quot;versao&quot;:&quot;1.0.0&quot;,
        ///	&quot;id_processo&quot;:&quot;|id|&quot;,
        ///	&quot;filial&quot;:&quot;|filial|&quot;, 
        ///	&quot;cnpj&quot;:&quot;|cnpj|&quot;,
        ///	&quot;prefixo&quot;:&quot;|prefixo|&quot;, 
        ///	&quot;numero&quot;:&quot;|numero|&quot; ,
        ///	&quot;parcela&quot;:&quot;|parcela|&quot;,
        ///	&quot;tipo&quot;:&quot;|tipo|&quot;, 
        ///	&quot;cliente&quot;:&quot;|cliente|&quot;,
        ///	&quot;loja_cli&quot;:&quot;|loja_cli|&quot;, 
        ///	&quot;num_ncc&quot;:&quot;|num_ncc|&quot;,
        ///	&quot;dt_devolucao&quot;:&quot;|dt_devolucao|&quot;,
        ///	&quot;vlr_devolucao&quot;:|vlr_devolucao|
        ///}.
        /// </summary>
        internal static string json_devolucao {
            get {
                return ResourceManager.GetString("json_devolucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;titulos&quot; : [
        ///		{
        ///			&quot;operacao&quot;:&quot;antecipacao&quot;,
        ///			&quot;versao&quot;:&quot;1.0.0&quot;,
        ///			&quot;id_processo&quot;:&quot;99999999999999999999999999999999&quot;,
        ///			&quot;filial&quot;:&quot;99999999&quot;, 
        ///			&quot;cnpj&quot;:&quot;99999999999999&quot;,
        ///			&quot;prefixo&quot;:&quot;1&quot;, 
        ///			&quot;numero&quot;:&quot;000000001&quot; ,
        ///			&quot;parcela&quot;:&quot;1&quot;,
        ///			&quot;tipo&quot;:&quot;NF&quot;, 
        ///			&quot;cliente&quot;:&quot;000001&quot;,
        ///			&quot;loja_cli&quot;:&quot;01&quot;, 
        ///			&quot;banco&quot;:&quot;000&quot;,  
        ///			&quot;agencia&quot;:&quot;00000&quot;, 
        ///			&quot;conta&quot;:&quot;0000000000&quot;,
        ///			&quot;dt_pg_antecip&quot;:&quot;20191215&quot;, 
        ///			&quot;tx_antecip&quot;:5.0 
        ///		},
        ///		{
        ///			&quot;operacao&quot;:&quot;antecipacao&quot;,
        ///			&quot;versao&quot;:&quot;1.0.0&quot;,
        ///			&quot;id_p [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string json_geral {
            get {
                return ResourceManager.GetString("json_geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;operacao&quot;:&quot;prorrogacao&quot;,
        ///	&quot;versao&quot;:&quot;1.0.0&quot;,
        ///	&quot;id_processo&quot;:&quot;|id|&quot;,
        ///	&quot;filial&quot;:&quot;|filial|&quot;, 
        ///	&quot;cnpj&quot;:&quot;|cnpj|&quot;,
        ///	&quot;prefixo&quot;:&quot;|prefixo|&quot;, 
        ///	&quot;numero&quot;:&quot;|numero|&quot; ,
        ///	&quot;parcela&quot;:&quot;|parcela|&quot;,
        ///	&quot;tipo&quot;:&quot;|tipo|&quot;, 
        ///	&quot;cliente&quot;:&quot;|cliente|&quot;,
        ///	&quot;loja_cli&quot;:&quot;|loja_cli|&quot;, 
        ///	&quot;dt_vencto&quot;:&quot;|dt_vencto|&quot;,
        ///	&quot;vlr_prorrogacao&quot;:|vlr_prorrogacao|
        ///}.
        /// </summary>
        internal static string json_prorrogacao {
            get {
                return ResourceManager.GetString("json_prorrogacao", resourceCulture);
            }
        }
    }
}
